# For more information, see:
# http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5,
# nightly-2015-09-21, ghc-7.10.2)
resolver: lts-13.22

# Local packages, usually specified by relative directory name
packages:
  - .

# Packages to be pulled from upstream that are not in the resolver (e.g.,
# acme-missiles-0.3)
extra-deps:
  - git: https://dev.angeley.es/s/fr33domlover/r/yesod-auth-account
    commit: 2d19eea0fae58897a02372a84cc48e7696a4e288
  - ./lib/darcs-lights
  - ./lib/darcs-rev
  - ./lib/dvara
  - ./lib/ssh
  - ./lib/hit-graph
  - ./lib/hit-harder
  - ./lib/hit-network
  - ./lib/http-client-signature
  - ./lib/http-signature
  - ./lib/persistent-email-address
  - ./lib/persistent-graph
  - ./lib/persistent-migration
  - ./lib/time-interval-aeson
  - ./lib/yesod-http-signature
  - ./lib/yesod-mail-send

  - DRBG-0.5.5
  - SimpleAES-0.4.2
  - darcs-2.14.2
  - data-default-instances-bytestring-0.0.1
  - esqueleto-2.7.0
  - git-0.3.0
  - graphviz-2999.20.0.3
  - highlighter2-0.2.5
  - libravatar-0.4.0.2
  - monad-hash-0.1.0.2
  - monadcryptorandom-0.7.2.1
  - patience-0.2.1.1
  - pwstore-fast-2.4.4
  - sandi-0.5
  - email-validate-json-0.1.0.0
  - time-interval-0.1.1
  - time-units-1.0.0
  - url-2.1.3

# Override default flag values for local packages and extra-deps
flags:
  vervis:
    dev: true

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
